### ISSUE TITLE
Determine Project License

### ISSUE THREAD

**Issue by intelagense** [intelagense/howdy#2]
## Description:
We need to decide on the appropriate open-source license for our project. This license will define how others can use, modify, and distribute our code. Choosing the right license is crucial for protecting our work and making it easier for others to contribute.

This issue is perfect for beginners who want to get involved in the foundational aspects of open-source projects. Researching and understanding licenses is a valuable skill in the open-source community.

### Acceptance Criteria:

- Research various open-source licenses and understand their implications.
- Discuss and evaluate the following popular licenses:
  - MIT License
  - Apache License 2.0
  - GNU General Public License (GPL)
  - BSD 3-Clause License
  - Creative Commons licenses (for documentation)
  - Any additional licenses that might be relevant to our project
- Recommend the best license for our project based on our goals and needs.
- Provide a brief explanation of why the recommended license was chosen.
- Create a LICENSE.md file with the chosen license text.

**Important Note:**
Here are some considerations to keep in mind when researching licenses:

- Compatibility with other projects and dependencies.
- The level of freedom we want to grant users.
- Whether we want to require modifications to also be open source.
- The need to protect trademarks or patents.

### Additional Resources:
[Choose an open source license](https://choosealicense.com/) guide
For more detailed guidance on contributing to open source, refer to [Open Source Guides](https://opensource.guide/).

### Deadline:
Please complete this task within 1 week of assignment.

Thank you for contributing and happy coding!

**Comment by jzipcode** [comment]
Hii Eric, can I do this one too, please?? (give me that! mine! me!!!)

**Comment by wgcv** [comment]
After talking we saw that the licenses:
- MIT License
- Apache License 2.0
- BSD 3-Clause License

Are more open that we want, because you can change the license with a fork.

**Comment by DaPandamonium** [comment]
# MIT License

- **Permissiveness**: Allows for broad usage and contribution, which is ideal for a project like a Discord bot that may need frequent updates and community contributions.
- **Simplicity**: Easy for contributors to understand and comply with.
- **Compatibility**: Works well with a variety of other open-source licenses and dependencies.
- **Community Adoption**: Encourages widespread adoption and use without significant legal overhead.

# GNU General Public License v3.0 (GPL-3.0)

- **Copyleft**: Requires that any derivative work be licensed under the same license.
- **Freedom**: Ensures that the code and its modifications remain free and open.
- **Patent Protection**: Provides protection against patent claims.
- **Use Cases**: Best for projects that aim to ensure all derivatives remain open-source and free.

- **Considerations**: If you want to ensure all modifications and derivative works of the "howdy" project remain open-source, GPL-3.0 is suitable.
- **Constraints**: May limit commercial use or integration with non-GPL compatible software.
