### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by intelagense** [intelagense/howdy#3]
## Description:

We are looking to create a CONTRIBUTING.md file to provide clear guidelines for contributing to our project. This is a great opportunity for beginners to get involved and learn about open source collaboration.

### Acceptance Criteria:

**The CONTRIBUTING.md file should include:**
- A welcome message thanking contributors for their interest.
- Guidelines for reporting bugs, including how to check for existing issues and the information to include when opening a new issue.
- Instructions for suggesting enhancements, including how to submit ideas and what details to provide.
- Steps for submitting pull requests, including forking the repository, creating a new branch, committing changes with descriptive messages, pushing to the fork, and opening a pull request.
- Any coding standards or style guidelines that contributors should follow.
- Contact information or resources for further questions or help.

### Notes:
Look at CONTRIBUTING.md files from other similar projects for inspiration.
Ensure the language is clear and easy to understand for all contributors, including those who may not be native English speakers.

Example of a Good CONTRIBUTING.md File:
[Daily Dev contributing docs](https://github.com/dailydotdev/.github/blob/master/CONTRIBUTING.md)

### Additional resources:
Here is a basic guide for formatting text in readme files using [GitHub Flavored Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)
For more detailed guidance on writing a README.md file and contributing to open source, refer to [Open Source Guides](https://opensource.guide/).
Free guides fow writting using the [Plain English Standard](https://www.plainenglish.co.uk/free-guides.html)

### Deadline:
Please complete this task within 1 weeks of assignment.

Thank you for contributing and happy coding!

**Comment by wgcv** [comment]
Solved with the PR #4
